# Generated by Django 6.0.7 on 2026-07-09 20:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique uuid id', primary_key=True, serialize=False, verbose_name='UUID id')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique uuid id', primary_key=True, serialize=False, verbose_name='UUID id')),
                ('title', models.CharField(max_length=25, unique_for_date='created_at', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.TextField(verbose_name="Task's description")),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], max_length=12, verbose_name='Status')),
                ('deadline', models.DateTimeField(verbose_name='DEADLINE')),
                ('categories', models.ManyToManyField(help_text='Category for every task', related_name='tasks', to='tasks.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique uuid id', primary_key=True, serialize=False, verbose_name='UUID id')),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title')),
                ('description', models.TextField(verbose_name="Subtask's description")),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], max_length=12, verbose_name='Status')),
                ('deadline', models.DateTimeField(verbose_name='DEADLINE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('task', models.ForeignKey(help_text='Subtask for the main task', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
