# Generated by Django 6.0.7 on 2026-07-15 19:27

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='category',
            name='unique_category_name',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_category_name', violation_error_message='Such a Category already exists!'),
        ),
        migrations.AlterConstraint(
            model_name='subtask',
            name='unique_subtask_title_by_creation_date',
            constraint=models.UniqueConstraint(models.F('title'), django.db.models.functions.datetime.TruncDate('created_at'), name='unique_subtask_title_by_creation_date', violation_error_message='Such a SubTask already exists!'),
        ),
        migrations.AlterConstraint(
            model_name='task',
            name='unique_title_by_creation_date',
            constraint=models.UniqueConstraint(models.F('title'), django.db.models.functions.datetime.TruncDate('created_at'), name='unique_title_by_creation_date', violation_error_message='Such a Task already exists!'),
        ),
    ]
